### ISSUE TITLE
Questions about end2end time cost of the inference request

### ISSUE THREAD

**Issue by littletomatodonkey** [Infini-AI-Lab/TriForce#5]
Hi, thanks for your great job for LLM decoding process. I tested the code and got the expected decoding speedup for llama2-7B, but it seems that the end2end time cost does not change too much? (61s -> 58s). I profile the inference process and it seems that the prefill process occupied the vast majority of inference time. Is the conclusion same with your experiments? Thanks !

```
Method: TriForce
Dataset: gs
Spec Args: {'budget': 4096, 'chunk_size': 8}
Draft: /mnt/bn/multimodel/models/official/llama-68m
Target: /mnt/bn/multimodel/models/official/NousResearch--Yarn-Llama-2-7b-128k/model
Prefill Length: 124928
Generation Length: 256
Gamma: 6
Sampling Method: top_k = -1, top_p = 0.9, temperature = 0.6
Log CSV: None
######################################################################################

[draft run] capturing graph for 0 (probs=True, temp=0.6, top_p=0.9)...
[draft run] capturing graph for 1 (probs=True, temp=0.6, top_p=0.9)...
[draft run] capturing graph for 2 (probs=True, temp=0.6, top_p=0.9)...
[draft run] capturing graph for 3 (probs=True, temp=0.6, top_p=0.9)...
[draft run] capturing graph for 4 (probs=True, temp=0.6, top_p=0.9)...
[draft run] capturing graph for 5 (probs=True, temp=0.6, top_p=0.9)...
[draft run] capturing graph for 6 (probs=True, temp=0.6, top_p=0.9)...
[draft run] capturing graph for 7 (probs=True, temp=0.6, top_p=0.9)...
[draft run] capturing graph for 8 (probs=True, temp=0.6, top_p=0.9)...
[model verify] capturing graph for spec len 6 (probs=True, temp=0.6, top_p=0.9)...
[Full Cache] Cached: 0 | Budget: 125200
[Retrieval Cache] Budget: 4096  | PreFill: 124928  | Chunk Size: 8  | Chunks: 15616  | Select Sets: 512
[StreamingLLM Cache] Start Size: 16 | Recent Size: 234 | Gamma: 6 | Real Budget: 259 | Cached: 0
tokenized_prompts length: 20
Autoregressive Warmup: 100%|████████████████████████████████████████████████| 1/1 [01:01<00:00, 61.31s/it]
Autoregressive Test: 100%|██████████████████████████████████████████████████| 1/1 [01:01<00:00, 61.73s/it]
[Autoregressive] average latency: 51.494828425347805 ms
TriForce Warmup: 100%|██████████████████████████████████████████████████████| 3/3 [02:53<00:00, 57.91s/it]
TriForce Test: 100%|██████████████████████████████████████████████████████| 20/20 [19:33<00:00, 58.66s/it]
average acceptance rate (NOT per token): 0.7204096470358102
[TriForce] average latency: 24.157854936546297 ms
[E2E Speedup]: 2.1315977167925535
```

**Comment by preminstrel** [comment]
Thank you for your interest in our research!

To clarify, our algorithm is designed for decoding acceleration, not pre-filling. For the pre-fill phase, we use a straightforward iterative method to avoid out-of-memory errors. Thus, our focus is on optimizing the **decoding (generation)** stage rather than **encoding (prompting)**.

There are numerous approaches to achieve time-efficient and memory-efficient pre-filling, which are orthogonal to our work. You may consider combining these approaches for a faster pre-fill phase. If you find an efficient method for pre-filling, there's no need for iterative pre-filling as we do. Alternatively, you can adjust the iteration settings in our code to manage your GPU's HBM efficiently.

And according to your log, seems you got 2.13x for decoding speedup. I think it is within expectation.

**Comment by littletomatodonkey** [comment]
Got it, thanks for your reply!

**Comment by wutong4012** [comment]
Sorry to bother you. Thank you for your contribution to the open source community. @preminstrel 
My experimental results are consistent with the issue, and I have no doubt about the speed of improvement.
However, as for the acceptance rate, I saw that the results reported in the paper are 90%+, but the actual test is only 70%. Why is this?
![image](https://github.com/user-attachments/assets/01bd2c80-bf14-46c4-9105-438cafe33475)

**Comment by preminstrel** [comment]
The reported acceptance rate is for per token acceptance rate. I guess your 70% is for a speculation length. @wutong4012

**Comment by wutong4012** [comment]
Thanks for your reply. I misunderstood because I saw the average acceptance rate in the table.
![image](https://github.com/user-attachments/assets/1d64c696-0d47-4604-93e9-b52657e06e70)

Could you please tell me how to calculate the per token acceptance rate?
And what are the benefits of doing so?

**Comment by preminstrel** [comment]
Average acceptance rate means per token acceptance rate averaged across samples. You can directly set $\gamma=1$ to get the per token acceptance rate or to solve an equation mentioned here. @wutong4012 

<img width="683" alt="image" src="https://github.com/user-attachments/assets/0522145c-f8b6-454f-99ab-5068ad36d369">

**Comment by wutong4012** [comment]
Got it, it was totally my fault, I didn't read the Google paper carefully.
Thanks for your reply, it's a good paper :)
